Abdul/app service blinky
microsoft/Windows-IoT-Samples pull request #34
Opened 2021-05-31 09:07 UTC by v-abdrahman

Created a folder for AppServiceBlinky app & added all the project files for windows 10 Iot Enterprise.

Following changes are done:

1) file modified : BlinkyService.vcxproj
    TargetPlatformVersion from 10.0.17763.0 to 10.0.19041.0 and TargetPlatformMinVersion from 10.0.10240.0 to 10.0.15063.0.

2) file modified : BlinkyClient.vcxproj
    TargetPlatformVersion from 10.0.17763.0 to 10.0.19041.0 and TargetPlatformMinVersion from 10.0.10240.0 to 10.0.15063.0.

3) file modified : BlinkyService.csproj
    TargetPlatformVersion from 10.0.17763.0 to 10.0.19041.0 and TargetPlatformMinVersion from 10.0.10240.0 to 10.0.15063.0.

4) file modified : BlinkyClient.csproj
    TargetPlatformVersion from 10.0.17763.0 to 10.0.19041.0 and TargetPlatformMinVersion from 10.0.10240.0 to 10.0.15063.0.

2) file modified : README.md
    Adding windows 10 iot Enterprise in products.
    Updated the Windows Platform from IoT Core to IoT Enterprise
    Added the BIOS setting for UPBOARD Pin configuration
    Added the app *packages installing steps

2021-06-11 20:33 UTC, neilsh-msft requested changes

2021-06-11 20:33 UTC, neilsh-msft commented on AppServiceBlinky/CPP/README.md
> +* You can find the source code for this sample by downloading a zip of all of our samples in WIndows 10 IoT Enterprise folder and navigating to the `samples-develop\AppServiceBlinky`.
Typo in "WIndows 10"  should be "Windows 10".

2021-06-11 20:33 UTC, neilsh-msft commented on AppServiceBlinky/CPP/README.md
> +* If it doesnot any value output, You will get the value by marking the breakpoint in debug mode for #StartupTask.cs at System.Diagnostics.Debug.WriteLine("Service closed. Status=" + args.Status.ToSt
typo in "doesnot", should be "does not"

2021-06-11 20:33 UTC, neilsh-msft commented on AppServiceBlinky/CPP/README.md
> +With the application open in Visual Studio 2019, set the architecture in the toolbar dropdown. If you’re building for UpBaord, select `x64`.
typo in "UpBaord".  I think we've agreed on "UP Board".

2021-06-14 07:06 UTC, rsameser approved these changes

2021-06-14 07:07 UTC, merged